var express = require('express')
const { getCategories, Addcategorie, UpdateCategorie, DeleteCategorie, DeleteManyCategories } = require('../controllers/categorieController')
const { categorievalidation, validation } = require('../middleware/validation')
var categorieRoute = express.Router()
categorieRoute.get('/all',getCategories)
categorieRoute.post('/addcategorie',categorievalidation,validation,Addcategorie)
categorieRoute.put('/updatecatg/:id',categorievalidation,validation,UpdateCategorie)
categorieRoute.delete('/deletecatg/:id',DeleteCategorie)
categorieRoute.delete('/deletemanycatg',DeleteManyCategories)
module.exports = categorieRoute 