var express = require('express')
const { getCustomer, Register, UpdateUser, getuser,DeleteUser, LoginCustomer } = require('../controllers/CustomerController')
const { customervalidation, validation, loginvalidation } = require('../middleware/validation')
const { IsAuthCustomer } = require('../middleware/IsAuth')
const { sendEmail } = require('../controllers/Nodemailer')
 var customerRoute = express.Router()
customerRoute.get('/all',getCustomer)
customerRoute.post('/register',customervalidation,validation,Register)
customerRoute.post('/login',loginvalidation,validation,LoginCustomer)
customerRoute.put('/update/:id',UpdateUser)
customerRoute.delete('/deletcustomer/:id',DeleteUser)
customerRoute.get('/user/:id',getuser)
customerRoute.post("/sendemail",sendEmail)
customerRoute.get('/getcurrent',IsAuthCustomer,(req,res)=>{
    res.send(req.user)
})
module.exports = customerRoute