export const GETCATEGORIE = 'GETCATEGORIE'
export const ADDCATEGORIE = 'ADDCATEGORIE'
export const ONECATEGORIE = 'ONECATEGORIE'
export const ALLPRODUCT="ALLPRODUCT"
export const ONEPRODUCT="ONEPRODUCT"