export const REGISTERCUSTOMER ='REGISTERCUSTOMER'
export const LOGINCUSTOMER ='LOGINCUSTOMER'
export const ALLCUSTOMER= 'ALLCUSTOMER'
export const GETUSERCUSTOMER = 'GETUSERCUSTOMER'
export const GETCURRENTCUST='GETCURRENTCUST'
 